
package com.bp.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloImpl", targetNamespace = "http://service.bp.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloImpl {


    /**
     * 
     * @return
     *     returns com.bp.service.PeopleInfoResponse.Return
     */
    @WebMethod
    @WebResult(name = "_return", targetNamespace = "")
    @RequestWrapper(localName = "peopleInfo", targetNamespace = "http://service.bp.com/", className = "com.bp.service.PeopleInfo")
    @ResponseWrapper(localName = "peopleInfoResponse", targetNamespace = "http://service.bp.com/", className = "com.bp.service.PeopleInfoResponse")
    public com.bp.service.PeopleInfoResponse.Return peopleInfo();

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayNextNum", targetNamespace = "http://service.bp.com/", className = "com.bp.service.SayNextNum")
    @ResponseWrapper(localName = "sayNextNumResponse", targetNamespace = "http://service.bp.com/", className = "com.bp.service.SayNextNumResponse")
    public int sayNextNum(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://service.bp.com/", className = "com.bp.service.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service.bp.com/", className = "com.bp.service.SayHelloResponse")
    public void sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "helloPeople", targetNamespace = "http://service.bp.com/", className = "com.bp.service.HelloPeople")
    @ResponseWrapper(localName = "helloPeopleResponse", targetNamespace = "http://service.bp.com/", className = "com.bp.service.HelloPeopleResponse")
    public List<Object> helloPeople();

}
